name: validate
on: pull_request

# Set globally scoped environmental variables.
env:
  ISSUE_NUMBER: ${{ github.event.pull_request.number }}
  PR_URL: https://github.com/obspy/obspy/pull/${{ github.event.pull_request.number }}
  CI_URL: https://github.com/obspy/obspy/actions/runs/${{ github.run_id }}
  CONFIG_PATH: obspy_ci_config/conf.json
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  # Parse the comments from the PR and uploads a json with selected options
  get_ci_config:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: create ci config
        shell: bash -l {0}
        run: |
          pip install git+https://github.com/d-chambers/obspy_github_api@gh-actions
          obshub make-config ${ISSUE_NUMBER} --path=${CONFIG_PATH} --token=${GITHUB_TOKEN}

      - name: upload ci config
        uses: actions/upload-artifact@v1
        with:
          name: obspy_ci_config
          path: ${{ env.CONFIG_PATH }}

  # Simply applies flake8 to the codebase.
  lint_code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: flake8
        run: |
          pip install wheel
          pip install flake8
          python -m flake8 obspy

  # Runs the tests on combinations of the supported python/os matrix.
  test_code:
    runs-on: ${{ matrix.os }}
    needs: get_ci_config
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v1

      - name: Setup conda
        uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: 'latest'
          python-version: ${{ matrix.python-version }}
          activate-environment: test
          environment-file: .github/test_conda_env.yml

      - name: print package info
        shell: bash -l {0}
        run: |
          conda info -a
          conda list

      - name: download test config
        uses: actions/download-artifact@v1
        with:
          name: obspy_ci_config

      - name: run test suite
        shell: bash -l {0}
        run: |
          export MODULELIST=`obshub get_config_value module_list --path=${CONFIG_PATH}`
          export MODULELISTSPACES=`obshub get_config_value module_list_spaces --path=${CONFIG_PATH}`
          coverage run --rcfile=.coveragerc --source=${MODULELIST} -m obspy.scripts.runtests --no-flake8 -n gh-actions -r --ci-url="${CI_URL}" --pr-url="${PR_URL}" $MODULELISTSPACES;

      - name: upload coverage
        uses: codecov/codecov-action@v1
        with:
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false


# This is a very useful step for debugging, it allows you to ssh into the CI
# machine (https://github.com/marketplace/actions/debugging-with-tmate).
# Make sure to open the log before the job starts else you cant see the tmate
# url. See https://github.com/mxschmitt/action-tmate/issues/1.
# Also, the CI machine will close on a non-zero exit code (annoying). This can
# be overcome by coalescing the null command like so:
# $ some-command-that-can-fail || :
#
#- name: Setup tmate session
#  uses: mxschmitt/action-tmate@v1
